### PR TITLE
travis caching, setup.py test, updates psi4 travis

### PR DESCRIPTION
**Pull request by loriab**
* institute caching of conda pkgs for travis
* allow `python setup.py test` to run pytest
* try dftd3 and psi4 pinnings after v1.3 release

### CODE REVIEW

**Comment by loriab** [comment]
This is ready for consideration. definitely SQUASH

**Comment by dgasmith** [comment]
Missing `codecov` at the end. Looks like ~3 minutes to pull from the cache so a win, but not massive.

**Comment by dgasmith** [comment]
6GB cache... killed that one off.

**Comment by loriab** [comment]
this cacheing thing is more involved than I expected. have fixed the codecov by moving it to `before_cache` (https://docs.travis-ci.com/user/job-lifecycle). but I suspect the lgtm hang is the same problem, and I'm not seeing a handle to adjust that. finding nothing in their forum either. any suggestions before posting there?

**Comment by loriab** [comment]
hooray, lgtm _wasn't_ hung!

I pushed one more commit to get a with-caching timing run. then this should be ready to go.

w/o cacheing
screen shot 2019-03-04 at 7 16 29 pm

**Comment by loriab** [comment]
hmpf, for all that, no change.
screen shot 2019-03-04 at 8 51 09 pm

**Comment by dgasmith** [comment]
It uploaded new packages at the end which took 2-4 minutes. Conda may be too active of a project.. unsure if it can do delta diffs

**Comment by loriab** [comment]
oh, wait. that `blas-mkl` pkg was a new one I added last commit. didn't even think about it changing the cache. one more try ...

**Comment by dgasmith** [comment]
Rebuilding, worth getting in and trying for a bit still I think. We have had enough Conda pull issues lately that it might at least help stabilize things.

**Comment by loriab** [comment]
yup, I tried a rebuild, too. Apart from the `1.4a1.dev11`, which was to be expected after last night, I got those `.q` and `.json` files (which made the cache reupload). Not sure what they are, and the psi4 travis doesn't have them. perhaps a history feature of a new conda/miniconda version. maybe can get rid of them. but yes, I think that can be later examination, and this is RTG.

screen shot 2019-03-05 at 10 44 01 am

**Pull request merged**
