### PR TITLE
Enable geometry optimizations with MRChem

### PR DESCRIPTION
**Pull request by robertodr**
## Description
I've modified the MRChem harness to accept input for the calculation of molecular gradients, which allows to use it with geometry optimization procedures.

## Changelog description
- MRChem can be used as engine for geometry optimizations.

## Status

- [X] Code base linted
- [X] Ready to go

### CODE REVIEW

**Comment by WardLT** [comment]
Could you add a test that shows it works?

**Comment by loriab** [comment]
Thanks, this lgtm, though I agree a test would be nice. If you release https://github.com/MolSSI/QCEngine/blob/master/qcengine/tests/test_harness_canonical.py#L83, I think the MRChem lane should pass. And if you rebase (I got a branch merged last night), I think the other lanes should pass.

I'm planning to do a release today. But if this doesn't make it in, there'll probably be another before the month is out.

**Comment by robertodr** [comment]
Sorry for the sloppy work! I've added tests for the evaluation of the gradient and running geometry optimizations.

**Comment by robertodr** [comment]
I'm pretty sure the OpenMM failure is unrelated.

**Review by loriab — APPROVED** [review]
lgtm, thanks for the new capability and the tests!

I've confirmed that OpenMM lane is failing on master, too, and asked someone to take a look.

**Comment by loriab** [comment]
Modernizing the yaml loading fixes the OpenMM lane somehow, so I think this is ready to go. Any other comments or concerns, @WardLT ?

**Comment by WardLT** [comment]
Looks great! Thanks @robertodr !

**Pull request merged**
