### PR TITLE
Refactor torsiondrive for easy parallel subclass

### PR DESCRIPTION
**Pull request by jthorton**
## Description

This PR refactors the running of the optimizations for the torsiondrive procedure into a function that can be easily overridden by users who would like to implement a parallel version. This avoids users having to deal with the inner workings of the torsiondrives and can instead focus on the distribution of the optimization tasks. 

## Changelog description

The torsiondrive procedure has been refactored to make it easier for users to implement a parallel version via subclassing and overwriting the `_spawn_optimizations` method.

cc @SimonBoothroyd 

## Status

- [X] Code base linted
- [x] Ready to go

### CODE REVIEW

**Review by dotsdl — APPROVED** [review]
Looks great to me @jthorton! Thank you for putting this together!

**Comment by dotsdl** [comment]
@loriab it looks like Python 3.6 for xtB is blocking us here? Where is the CI running? Does it not exist anymore and need to be removed from required checks?

**Comment by loriab** [comment]
I remember seemingly removing xtb 3.6 a couple times and GH not being convinced. go ahead and merge when ready, and I'll take another look at required checks tomorrow.

**Comment by dotsdl** [comment]
Thanks @loriab! Unfortunately I don't have sufficient permissions on this repo to merge without that check. I can't click the merge button. :cry:

**Comment by loriab** [comment]
> Thanks @loriab! Unfortunately I don't have sufficient permissions on this repo to merge without that check. I can't click the merge button. 😢

See if merge clear now, @dotsdl

**Comment by dotsdl** [comment]
It works! Thanks @loriab!

**Pull request merged**
