### PR TITLE
Molpro: (WIP) Added CCSD support to output parsing

### PR DESCRIPTION
**Pull request by sjrl**
Added CCSD support to output parsing. However, it looks like the ccsd keys (same as mp2 except with the ccsd label) need to be added to the supported keys. I believe in QCSchema?

- [ ] Add support to QCSchema (?) for CCSD quantities

### CODE REVIEW

**Comment by dgasmith** [comment]
Yes, we have not yet added CCSD keys to the QCSchema. Should be a pretty simple add, you can open a PR modifying [here](https://github.com/MolSSI/QCElemental/blob/master/qcelemental/models/results.py#L41) if you wish.

**Comment by sjrl** [comment]
While I was working on this today, I realized I may have mapped the Molpro and Molssi quantities incorrectly. Do you know if `opposite_spin_correlation` is the same as `singlet pair energy` or `triplet pair energy` (which is the notation used in Molpro. Doing a quick search I couldn't easily see how the naming conventions match up.

**Comment by loriab** [comment]
Yes, Molpro --> Psi4 (which in this case "wins" on precedent) needs a bit of math for same-spin/opposite-spin quantities.

```
            #}   
            if ($line =~ /CCSD correlation energy/) {
               @ltemp = split( /\s+/, $line);
               $tempc = @ltemp[4];
            }
            if ($line =~ /Total correlation energy/) {
               @ltemp = split( /\s+/, $line);
               $tempd = @ltemp[4];
            }
            if ($line =~ /MP2 triplet pair energy/) {
               @ltemp = split( /\s+/, $line);
               $tempf = @ltemp[5];
            }
            #if ($line =~ / TEMP3            = /) {  # only printed with special instructions
            #   @ltemp = split( /\s+/, $line);
            #   $temph = @ltemp[3];
            #}
            if ($line =~ /CCSD triplet pair energy/) {
               @ltemp = split( /\s+/, $line);
               $tempg = @ltemp[5];
            }
         }  

         $tempf *= 2/3;
         #$temph *= 2/3;
         $tempg *= 2/3;
```

**Comment by sjrl** [comment]
Sorry I'm still a little confused. Are the final `$tempf` and `$tempg` quantities the conversion between triplet pair energy and the same spin energy?

**Comment by loriab** [comment]
something like that. if you can use a scaling with 2, 3 to get values like https://github.com/psi4/psi4/blob/master/tests/pytest/test_mp2.py#L13-L24 for https://github.com/psi4/psi4/blob/master/tests/pytest/test_mp2.py#L52-L54, you're in good shape.

**Comment by sjrl** [comment]
I think I have it `(1/3)*triplet + singlet = opposite` and `(2/3)*triplet = same`. I'll update my pull request with the correct conversion.

**Comment by dgasmith** [comment]
This looks good! We need to crank out a new QCElemental release soon so that this can go through.

**Comment by sjrl** [comment]
Okay sounds good! I'll keep an eye out for the QCElemental release.

**Comment by dgasmith** [comment]
QCElemental v0.4 is now out. Do we need to do anything here to get this in?

**Comment by sjrl** [comment]
It should be good to pull unless you'd like me to update it with the current master branch.

**Comment by dgasmith** [comment]
Please do, it's been long enough that we want to run this through CI once more.

**Comment by sjrl** [comment]
Okay everything looks good. Also just wanted to give a heads up, one of the testjobs I have added for Molpro does not pass, because it is unable to find the CCSD energy from the xml file when calling a gradient. I have an idea of how to fix this (maybe text parsing), but I was going to wait to fix that at a later date.

**Pull request merged**
