### PR TITLE
put stuff in the same place

### PR DESCRIPTION
**Pull request by loriab**
* registration occurs in `pro*/base.py` (change to programs)
* base class is `Pro*Harness` (change to procedures and programs)
* base class defined in `pro*/model.py` (change to both)
* ~add `register_program(..., check=True)` so I can override `qcng.compute(prog)` with a re-registered custom `ProgExecutor`-derived class~
* add glob collection of output files from `util.execute`

### CODE REVIEW

**Comment by loriab** [comment]
Errors are due to WIP #76. Locally, tests as expected. Will rebase after CI healed.

**Comment by loriab** [comment]
Regrettably, this PR has expanded (for ease of rebase). There's various cfour stuff but the other notable thing to review is is collecting output files by glob. All these go in a subdictionary of outfiles. Since I'm collecting file names by glob, then immediately reading them in, presently skipping the error checking. This is plain, not recursive, glob.

**Comment by loriab** [comment]
General, this tests as clean as expected locally, and the lgtm alerts aren't suitable for fixing, so this is ready for consideration.

@sjrl, FYI, I get the errors like the below during Molpro execution on a local Molpro 2010. Probably Molpro too old. It's not anything to pursue, just keep in mind if they pop up elsewhere.

```
--------------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------------
{'error': {'error_message': 'Last System Error Message from Task 0:: No such '
                            'file or directory\n'
                            'application called MPI_Abort(comm=0x84000004, 43) '
                            '- process 0\n'
                            'Last System Error Message from Task 1:: No such '
                            'file or directory\n'
                            'application called MPI_Abort(comm=0x84000002, 43) '
                            '- process 1\n'
                            'Last System Error Message from Task 2:: No such '
                            'file or directory\n'
                            'application called MPI_Abort(comm=0x84000002, 43) '
                            '- process 2\n'
                            'Last System Error Message from Task 3:: No such '
                            'file or directory\n'
                            'application called MPI_Abort(comm=0x84000002, 43) '
                            '- process 3\n',
           'error_type': 'internal_error',
```

```
>       assert result.success is True
E       AssertionError: assert False is True
E        +  where False = <FailedOperation error=<ComputeError error_type='unknown_error' error_message='QCEngine Execution Erro… id=None input_data={'molecule': {'symbols': ['O', 'H', 'H'], 'geometry': array([[ 0.        ,  0. … success=False extras=None>.success

qcengine/programs/tests/test_molpro.py:59: AssertionError
--------------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------------
{'error': {'error_message': 'QCEngine Execution Error:\n'
                            'Traceback (most recent call last):\n'
                            '  File '
                            '"/home/psilocaluser/gits/QCEngine/qcengine/util.py", '
                            'line 73, in compute_wrapper\n'
                            '    yield metadata\n'
                            '  File '
                            '"/home/psilocaluser/gits/QCEngine/qcengine/compute.py", '
                            'line 79, in compute\n'
                            '    output_data = executor.compute(input_data, '
                            'config)\n'
                            '  File '
                            '"/home/psilocaluser/gits/QCEngine/qcengine/programs/molpro.py", '
                            'line 83, in compute\n'
                            '    result = self.parse_output(proc["outfiles"], '
                            'input_data)\n'
                            '  File '
                            '"/home/psilocaluser/gits/QCEngine/qcengine/programs/molpro.py", '
                            'line 252, in parse_output\n'
                            "    mol_method = molecule.attrib['method']\n"
                            "AttributeError: 'NoneType' object has no "
                            "attribute 'attrib'\n",
           'error_type': 'unknown_error',
           'extras': None},
 'extras': None,
 'id': None,
 'input_data': {'driver': <DriverEnum.gradient: 'gradient'>,
                'extras': {},
                'id': None,
                'keywords': {},
                'model': {'basis': 'sto-3g', 'method': 'MP2'},
                'molecule': {'atom_labels': ['', '', ''],
                             'atomic_numbers': [8, 1, 1],
                             'connectivity': [(0, 1, 1.0), (0, 2, 1.0)],
                             'fix_com': False,
                             'fix_orientation': False,
                             'fragment_charges': [0.0],
                             'fragment_multiplicities': [1],
                             'fragments': [[0, 1, 2]],
                             'geometry': array([[ 0.        ,  0.        , -0.12947694],
       [ 0.        , -1.49418734,  1.02744651],
       [ 0.        ,  1.49418734,  1.02744651]]),
                             'mass_numbers': [16, 1, 1],
                             'masses': [15.99491461957,
                                        1.00782503223,
                                        1.00782503223],
                             'molecular_charge': 0.0,
                             'molecular_multiplicity': 1,
                             'name': 'H2O',
                             'provenance': {'creator': 'QCElemental',
                                            'routine': 'qcelemental.molparse.from_schema',
                                            'version': 'v0.4.0+7.gc6ec7e1.dirty'},
                             'real': [True, True, True],
                             'schema_name': 'qcschema_molecule',
                             'schema_version': 2,
                             'symbols': ['O', 'H', 'H']},
                'provenance': {'cpu': 'Intel(R) Xeon(R) CPU E5-2630 v4 @ '
                                      '2.20GHz',
                               'creator': 'QCElemental',
                               'hostname': 'psinet',
                               'qcengine_version': 'v0.6.3+95.gd046417.dirty',
                               'routine': 'qcelemental.models.results',
                               'username': 'psilocaluser',
                               'version': 'v0.4.0+7.gc6ec7e1.dirty',
                               'wall_time': 19.605295419692993},
                'schema_name': 'qcschema_input',
                'schema_version': 1},
 'success': False}
==
```

**Comment by sjrl** [comment]
Thanks for the heads up. It's probably worth getting the check version working for Molpro and figuring out how far back we can go with the current functions (and whether if we want to support older versions of Molpro).

**Pull request merged**
