### PR TITLE
slightly loosen xtb testing

### PR DESCRIPTION
**Pull request by loriab**
## Description
will this be ok, @awvwgk? it fixes CI.

## Status

- [x] Code base linted
- [x] Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
will this be ok, @awvwgk? it fixes CI. (sorry if double-ping -- I don't think GH pings on edits.)

**Comment by awvwgk** [comment]
I think the current threshold is relative rather than absolute (https://docs.pytest.org/en/6.2.x/reference.html#pytest.approx). I switched to `pytest.approx(..., abs=thr)` for testing in my projects since the relative comparison can fail for very small (numerical zero) values otherwise.

**Comment by awvwgk** [comment]
> sorry if double-ping -- I don't think GH pings on edits.

No problem. Looks like GH pings correctly for mentions in edits.

**Comment by loriab** [comment]
> I think the current threshold is relative rather than absolute (https://docs.pytest.org/en/6.2.x/reference.html#pytest.approx). I switched to pytest.approx(..., abs=thr) for testing in my projects since the relative comparison can fail for very small (numerical zero) values otherwise.

Sounds good -- it was checking some elements to 1e-11 before, so this is a sensible relaxation.

**Review by awvwgk — APPROVED** [review]

**Review by bennybp — APPROVED** [review]

**Pull request merged**
